apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.studio.nodeEnv | quote }}
  KWEAVER_HYDRA_ADMIN_URL: {{ .Values.studio.KWeaverHydraAdminURL | quote }}
  USE_EXTERNAL_OPENCLAW: {{ .Values.studio.useExternalOpenClaw | quote }}
  OPENCLAW_HOST_PATH: {{ .Values.studio.OpenClawHostPath | quote }}
  DB_SYSTEM_ID: {{ .Values.depServices.rds.system_id | quote }}
  DB_TYPE: {{ .Values.depServices.rds.type | quote }}
  DB_HOST: {{ .Values.depServices.rds.host | quote }}
  DB_PORT: {{ .Values.depServices.rds.port | quote }}
  DB_USER: {{ .Values.depServices.rds.user | quote }}
  DB_NAME: {{ .Values.depServices.rds.database | quote }}
