import { describe, expect, it } from "vitest";

import {
  containsNonAscii,
  isLosslessLatin1Utf8RoundTrip,
  normalizeMultipartFilename
} from "./upload";

describe("containsNonAscii", () => {
  it("returns false for ASCII-only names", () => {
    expect(containsNonAscii("report.txt")).toBe(false);
  });

  it("returns true for non-ASCII names", () => {
    expect(containsNonAscii("流程说明.md")).toBe(true);
  });
});

describe("isLosslessLatin1Utf8RoundTrip", () => {
  it("returns true for mojibake generated by latin1 decoding", () => {
    expect(
      isLosslessLatin1Utf8RoundTrip("æµ\x8Bè¯\x95.txt", "测试.txt")
    ).toBe(true);
  });

  it("returns false when decoding introduces replacement characters", () => {
    expect(isLosslessLatin1Utf8RoundTrip("café.txt", "caf�.txt")).toBe(false);
  });
});

describe("normalizeMultipartFilename", () => {
  it("keeps ASCII filenames unchanged", () => {
    expect(normalizeMultipartFilename("a.txt")).toBe("a.txt");
  });

  it("repairs mojibake UTF-8 filenames", () => {
    expect(normalizeMultipartFilename("æµ\x8Bè¯\x95.txt")).toBe("测试.txt");
  });

  it("preserves already-correct unicode filenames", () => {
    expect(normalizeMultipartFilename("测试.txt")).toBe("测试.txt");
  });

  it("preserves non-ASCII filenames that are not latin1-misdecoded UTF-8", () => {
    expect(normalizeMultipartFilename("café.txt")).toBe("café.txt");
  });
});
