namespace: kweaver

labels:
  deployment:
    name: dip-studio
  pod:
    app: dip-studio
  service:
    app: dip-studio

name: dip-studio-deployment
replicaCount: 1

image:
  registry: swr.cn-east-3.myhuaweicloud.com/kweaver-ai
  repository: dip/dip-studio
  tag: "0.5.0-main.22fefcd"
  pullPolicy: IfNotPresent

service:
  name: dip-studio
  type: ClusterIP
  port: 3000
  targetPort: 3000

class-443:
  ingressClass: 'class-443'

ingress:
  enabled: true
  path: /api/dip-studio
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "off"

studio:
  nodeEnv: production
  envFileHostPath: /root/.env
  openClawHostPath: /root/.openclaw/
  KWeaverBaseURL: http://bkn-backend-svc:13014
  KWeaverHydraAdminURL: http://hydra-admin:4445
  useExternalOpenClaw: false

resources:
  studio:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 4
      memory: 4Gi

nodeSelector: {}
affinity: {}
tolerations: []
