// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/kweaver-ai/idrm-go-common/audit"
	v1_2 "github.com/kweaver-ai/idrm-go-common/middleware/v1"
	v1 "github.com/kweaver-ai/idrm-go-common/rest/auth-service/v1"
	impl3 "github.com/kweaver-ai/idrm-go-common/rest/authorization/impl"
	impl2 "github.com/kweaver-ai/idrm-go-common/rest/configuration_center/impl"
	impl4 "github.com/kweaver-ai/idrm-go-common/rest/data_application_service/impl"
	impl5 "github.com/kweaver-ai/idrm-go-common/rest/data_view/impl"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/database"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/gorm"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/mq"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/mq/views"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/resources"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driven/workflow/custom"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driver"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/adapter/driver/v2/auth"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/common/settings"
	impl7 "github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/domain/common_auth/impl"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/infrastructure/mq/kafka"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/infrastructure/repository/db"
	"github.com/kweaver-ai/kweaver-dip/dsg/services/apps/auth-service/infrastructure/repository/redis"

	"github.com/kweaver-ai/idrm-go-common/rest/hydra/impl"
	impl6 "github.com/kweaver-ai/idrm-go-common/rest/indicator_management/impl"
	impl20 "github.com/kweaver-ai/idrm-go-common/rest/studio_web/impl"
	"github.com/kweaver-ai/idrm-go-common/rest/user_management"
	"github.com/kweaver-ai/idrm-go-common/trace"
	"github.com/kweaver-ai/idrm-go-common/workflow"
	idrm_go_frame "github.com/kweaver-ai/idrm-go-frame"
	"github.com/kweaver-ai/idrm-go-frame/core/transport/rest"
)

// Injectors from wire.go:

func InitApp(s *settings.Settings) (*AppRunner, func(), error) {
	client := trace.NewOtelHttpClient()
	hydra := impl.NewHydraByService(client)
	drivenUserMgnt := user_management.NewUserMgntByService(client)
	driven := impl2.NewConfigurationCenterDrivenByService(client)
	logger := audit.Discard()
	authorizationDriven := impl3.NewDriven(client)
	authServiceInternalV1Interface, err := v1.NewInternalForBase(client)
	if err != nil {
		return nil, nil, err
	}
	middleware := v1_2.NewMiddleware(hydra, drivenUserMgnt, driven, logger, authorizationDriven, authServiceInternalV1Interface)
	gormDB, err := db.NewMariaDB(s)
	if err != nil {
		return nil, nil, err
	}
	indicatorDimensionalRuleInterface := gorm.NewIndicatorDimensionalRuleInterfaceRepository(gormDB)
	redisClient := redis.NewRedisClient()
	data_application_serviceDriven := impl4.NewDrivenImpl(client)
	data_viewDriven := impl5.NewDataViewDriven(client)
	indicator_managementDriven := impl6.NewDrivenImpl(client)
	gormDBWithoutDatabase, err := db.NewGormDBWithoutDatabase(s)
	if err != nil {
		return nil, nil, err
	}
	databaseClient := database.New(gormDBWithoutDatabase)
	common_authAuth := impl7.NewAuth(authorizationDriven, redisClient, indicatorDimensionalRuleInterface, driven, data_application_serviceDriven, data_viewDriven, indicator_managementDriven, databaseClient, drivenUserMgnt)
	authController := auth.NewController(common_authAuth)
	mqConf, err := settings.WorkflowMQConfFor(s)
	if err != nil {
		return nil, nil, err
	}
	workflowInterface, err := workflow.NewWorkflow(client, mqConf)
	if err != nil {
		return nil, nil, err
	}
	router := &driver.Router{
		Middleware:       middleware,
		AuthV2Controller: authController,
	}
	server := driver.NewHttpServer(s, router)
	consumer := kafka.NewConsumer()
	authSubViewRepo := gorm.NewAuthSubViewRepo(gormDB)
	subViewHandler := views.NewSubViewHandler(authSubViewRepo)
	kafkaConsumer := mq.NewKafkaConsumer(consumer, subViewHandler)
	app := newApp(server, kafkaConsumer)
	consumeAuthRequestRepo := gorm.NewConsumeAuthRequestRepo(gormDB, client)
	wfConsumerRegister, err := custom.NewWFConsumerRegister(workflowInterface, consumeAuthRequestRepo)
	if err != nil {
		return nil, nil, err
	}
	studio_webDriven := impl20.NewDriven(client)
	registerClient := resources.NewRegisterClient(authorizationDriven, studio_webDriven)
	appRunner := &AppRunner{
		App:              app,
		nsq:              wfConsumerRegister,
		resourceRegister: registerClient,
	}
	return appRunner, func() {
	}, nil
}

// wire.go:

var appRunnerSet = wire.NewSet(wire.Struct(new(AppRunner), "*"))

func newApp(hs *rest.Server, consumer *mq.KafkaConsumer) *idrm_go_frame.App {
	return idrm_go_frame.New(idrm_go_frame.Name(Name), idrm_go_frame.Server(hs, consumer))
}
