apiVersion: deploy.kweaver.ai/v1alpha1
kind: VersionSet
product: kweaver-dip
version: 0.4.0
source:
  helmRepoName: kweaver
  helmRepoUrl: https://kweaver-ai.github.io/helm-repo/
  imageRegistry: swr.cn-east-3.myhuaweicloud.com/kweaver-ai
dependencies:
- product: isf
  version: 0.5.0
  manifest: ../0.5.0/isf.yaml
- product: kweaver-core
  version: 0.5.0
  manifest: ../0.5.0/kweaver-core.yaml
releases:
  dip-data-migrator:
    chart: dip-data-migrator
    version: 0.4.0-main.20260331.5.fac488b
    stage: pre
  anyfabric-frontend:
    chart: anyfabric-frontend
    version: 0.4.0-main.20260403.2
  dip-frontend:
    chart: dip-frontend
    version: 0.4.0-main.41dfacf
  auth-service:
    chart: auth-service
    version: 0.4.0-main.20260402.1
  basic-search:
    chart: basic-search
    version: 0.4.0-main.20260331.1
  configuration-center:
    chart: configuration-center
    version: 0.4.0-main.20260403.1
  data-application-gateway:
    chart: data-application-gateway
    version: 0.4.0-main.20260403.1
  data-application-service:
    chart: data-application-service
    version: 0.4.0-main.20260403.1
  data-catalog:
    chart: data-catalog
    version: 0.4.0-main.20260403.1
  data-exploration-service:
    chart: data-exploration-service
    version: 0.4.0-main.20260403.1
  data-semantic:
    chart: data-semantic
    version: 0.4.0-main.20260403.1
  data-subject:
    chart: data-subject
    version: 0.4.0-main.20260403.1
  data-view:
    chart: data-view
    version: 0.4.0-main.20260403.1
  sailor:
    chart: sailor
    version: 0.4.0-main.20260402.2
  sailor-agent:
    chart: sailor-agent
    version: 0.4.0-main.20260402.5
  sailor-service:
    chart: sailor-service
    version: 0.4.0-main.20260331.7
  session:
    chart: session
    version: 0.4.0-main.20260403.1
  standardization:
    chart: standardization
    version: 0.4.0-main.20260402.13
  task-center:
    chart: task-center
    version: 0.4.0-main.20260403.1
  dip-hub:
    chart: dip-hub
    version: 0.4.0
  dip-studio:
    chart: dip-studio
    version: 0.4.0-4
